### ISSUE TITLE
Model Render Component Issue

### ISSUE THREAD

**Issue by B0zy** [Facepunch/sbox-scenestaging#1]
Haven't been able to replicate as of today so I'm not sure if its fixed, but in some cases model render components ( even in the default .scene files) without any editing will have all their selected models replaced by `models/dev/error.vmdl_c` when launching the scenestaging project. 

Here's pictures of what I mean if I've explained it poorly. If I come across the actual error its self, I'll be sure to provide console logs

## Before
![image](https://github.com/Facepunch/sbox-scenestaging/assets/40073828/8e0b41c7-26f3-48b6-8f21-d836dc2b9a8c)

## After the Error 
![image](https://github.com/Facepunch/sbox-scenestaging/assets/40073828/97647045-71c3-4425-a27c-b1a44026ea46)

**Comment by garrynewman** [comment]
Please re-open when you can replicate

**Comment by DrakeFruit** [comment]
> Please re-open when you can replicate

looks like we can't re-open issues? (I didn't manage to replicate this but I just noticed it's not an option)
