### ISSUE TITLE
ToggleGroups with the same name as a property end up merging together strangely

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-scenestaging#102]
```CS
	[Property, ToggleGroup("Body")]
	public SkinnedModelRenderer Body { get; set; }
```

![image](https://github.com/Facepunch/sbox-scenestaging/assets/7847372/1882b785-4256-430a-bbb4-3563f9d2ba53)

You can see in this image the `Body` property is sort of crammed into the toggle group header.

**Comment by garrynewman** [comment]
This is by design
