### ISSUE TITLE
Dragging a reference to a component's property inside of a Prefab will spit an NRE and not save.

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-scenestaging#103]
I'll preface by saying it's pretty random, but there's times where restarting doesn't fix it.
Setting a reference property to a component inside a Prefab will give the following errors in console:
https://pastebin.com/raw/nW7jpnPx
https://pastebin.com/raw/6YQdah3P
(They're long so I used pastebin)

Here's the repository I'm on: https://github.com/Small-Fish-Dev/snot-farm/
It's pretty minimal, just open the snot_player.object inside of the scenes/snot_farm folder and try to replicate the following video:

https://github.com/Facepunch/sbox-scenestaging/assets/59583743/bd599599-a619-49ed-87d6-62cc7aa27292

In the video we have the default Player Controller component which takes in a Citizen Animation Helper, I drag the helper that's on the player's prefab and place it in the property field, then the error appears. Saving, closing, and reopening shows that it wasn't set at all.
The repository itself is just a fork of the scene-scenestaging and I made sure it was up to date with it.

This is the .log of the session:
[Log.log](https://github.com/Facepunch/sbox-scenestaging/files/13573229/Log.log)

**Comment by NotGaylien** [comment]
https://github.com/Facepunch/sbox-scenestaging/issues/66
This is actually what's causing it.
its creating the root game object with a unique ID,
but not storing its ID in the dictionary of game object that exists within the scene.

causing shit to freak out.
