### ISSUE TITLE
Example player controller ignores the `solid` layer

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-scenestaging#109]
A lot of people (including myself) use the player controller scene as a template.

![image-41.png](https://github.com/Facepunch/sbox-scenestaging/assets/91832803/f65e8b19-1122-44c5-a0a7-29cf4b98e3ac)

Because the provided character controller ignores the `solid` layer, you obviously fall through objects marked as solid i.e maps.

![Screenshot_20240105_105514_Discord.jpg](https://github.com/Facepunch/sbox-scenestaging/assets/91832803/d4969916-019e-4abe-b967-77c79f35f6ea)

![Screenshot_20240105_105529_Discord.jpg](https://github.com/Facepunch/sbox-scenestaging/assets/91832803/bf65d645-beb9-457e-ab0b-ae6f718673b1)

**Comment by Nolankicks** [comment]
I would make this on the s&box issues because the character controller is not specific to this repo. Its built into the game.
