### ISSUE TITLE
Components on the Scene Root are not saved

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-scenestaging#12]
Not even sure we're meant to be able to put components on the scene root, but they're not saved regardless.

1. place a component on the scene root, such as a point light
2. save the scene and then close it in the scene browser
3. components  are gone

https://github.com/Facepunch/sbox-scenestaging/assets/7847372/3c0355ea-97b6-4264-8d16-46f00646dd55

**Comment by DrakeFruit** [comment]
they definitely should be saved, scene root is just a GameObject (at least it should be, like the root node in Godot)
