### ISSUE TITLE
Scaling GameObject are link

### ISSUE THREAD

**Issue by SuperCoolNinja** [Facepunch/sbox-scenestaging#16]
When scaling a game object, it currently scales all three axes simultaneously.

We should have the ability to individually scale each axis, with an optional linking feature to maintain proportional scaling.

https://github.com/Facepunch/sbox-scenestaging/assets/28671231/7e82c4d0-4ecc-4f93-9d35-7357dc4052dd

**Comment by garrynewman** [comment]
None uniform scaling is on our wish list - but it needs significant engine changes to achieve.
