### ISSUE TITLE
Can't change the order of Components or Shrink the display for Components

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-scenestaging#19]
Changing the order of components by dragging and dropping them would be nice. Also noticed that you can't shrink components with the lil dropdown arrow:
![image](https://github.com/Facepunch/sbox-scenestaging/assets/7847372/9c0ea974-2a19-42f7-a507-a0e3857cc28c)

**Comment by DevulTj** [comment]
Added Shrink/Expand, not sure about the first one yet

**Comment by Fortune117** [comment]
I think CrayZ added ordering for components, thanks :>
