### ISSUE TITLE
Model Bounds Don't Follow Bone Merges

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-scenestaging#32]
If I set a game object as a child of a bone, you can see that it renders as expected:

https://github.com/Facepunch/sbox-scenestaging/assets/7847372/b7a70e37-61e0-4e94-8860-08c36c8fe2f3

However, if the model is bone merged, its bounds do not seem to be set properly:

https://github.com/Facepunch/sbox-scenestaging/assets/7847372/80f17bda-49aa-485f-84ba-9a70e5a4233a

In both these examples, the game object for the sword is following the hand bones.

My repo is here if it helps: https://github.com/Fortune117/sbox-scenestaging/tree/dark-descent

**Comment by garrynewman** [comment]
Is this still the case?

**Comment by Fortune117** [comment]
Yep
