### ISSUE TITLE
Component properties marked with `[Property]` don't accept sub classes

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-scenestaging#33]
I have a `CarriedItemComponent` property, and it won't accept the subclass component `CarriedWeaponComponent`

https://github.com/Facepunch/sbox-scenestaging/assets/7847372/91d9bcf1-4c09-4f9c-951d-bcb7c0b63ac7

**Comment by bub-bl** [comment]
Its working on my project. (Try to clone the latests changes from the main branch)
If its not working, look if your property have a setter

**Comment by Fortune117** [comment]
> Its working on my project. (Try to clone the latests changes from the main branch) If its not working, look if your property have a setter

Updated everything to latest and I still have the same issue.

Property is defined like this:
```CS
[Property]
private CarriedItemComponent ItemComponent { get; set; }
```
Doesn't accept the subclass `CarriedWeaponComponent` when I try and drag it on. If I change the type of the property to `CarriedWeaponComponent` it works fine.

**Comment by bub-bl** [comment]
> > Its working on my project. (Try to clone the latests changes from the main branch) If its not working, look if your property have a setter
> 
> Updated everything to latest and I still have the same issue.
> 
> Property is defined like this:
> ```CS
> [Property]
> private CarriedItemComponent ItemComponent { get; set; }
> ```
> Doesn't accept the subclass `CarriedWeaponComponent` when I try and drag it on. If I change the type of the property to `CarriedWeaponComponent` it works fine.

You try to set the `CarriedWeaponComponent` component on a `CarriedItemComponent` property ?

CarriedItemComponent inherits of CarriedWeaponComponent ?

I think, the Editor didnt check inheritance of class, so the Editor does not accept the type

Try to put that `[Property] private ICarriedComponent ItemComponent { get; set; }` instead

Implement `ICarriedComponent` for `CarriedItemComponent` and `CarriedWeaponComponent` and try again, i dont know if it works

**Comment by bub-bl** [comment]
After some tests with implementations/inheritance, this is not working. We can't set a property if the base type is not exactly the same.

**Comment by bub-bl** [comment]
To correct this problem while waiting for an official patch, you can use the following code:

- Go to the `testbed.editor` project
- Open the `GameObject.Component.cs` file
- Go to line 64, it should look like this:
```csharp
    /// <summary>
    /// Get a list of components on this game object, optionally recurse when deep is true
    /// </summary>
    public IEnumerable<BaseComponent> GetComponents(Type type, bool enabledOnly = true, bool deep = false)
    {
        return GetComponents<BaseComponent>(enabledOnly, deep).Where(x => x.GetType().IsAssignableFrom(type));
    }
```

Replace the code with this line:
```csharp
return GetComponents(enabledOnly, deep).Where(x => x.GetType().IsAssignableTo(type));
```

Your problem should be resolved
