### ISSUE TITLE
Physics shapes created by `ModelPhysicsComponent` do not have their surface property set from the vmdl.

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-scenestaging#39]
This bit goes unused.
![image](https://github.com/Facepunch/sbox-scenestaging/assets/7847372/0dd24c3b-6a42-40f4-8e48-38ed6965f5a8)

**Comment by Fortune117** [comment]
The surface property being set seems to always be null right now. Just tested it out and nothing I did on the model resulted in the parts surface being non-null.

Example from ModelCollider.cs
```CS
			foreach ( var sphere in part.Spheres )
			{
				Log.Info( sphere.Surface?.ResourceName ); //always prints null
				var shape = targetBody.AddSphereShape( bx.PointToWorld( sphere.Sphere.Center ), sphere.Sphere.Radius * bx.Scale );
				shape.Surface = sphere.Surface;
				yield return shape;
			}
```

**Comment by aylaylay** [comment]
These should be set now, can you test for me please?
