### ISSUE TITLE
Inspector doesn't scroll when there are a lot of components on a game object

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-scenestaging#41]
I've run out of room on my player game object, can't add new components and some components aren't accessible as they go out of frame.

![image](https://github.com/Facepunch/sbox-scenestaging/assets/7847372/dd20e06d-ad92-4a34-a54a-20a5fe7b4724)

**Comment by DevulTj** [comment]
Crayz added this now

**Comment by bakscratch** [comment]
Many thanks @cr4yz <3
