### ISSUE TITLE
Properties sometimes aren't serialized properly when the component is disabled

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-scenestaging#47]
~~Seems to happen fairly often with specifically the model physics renderer.~~

Seems to be because the component is disabled!

https://github.com/Facepunch/sbox-scenestaging/assets/7847372/21478247-e4fd-48d7-a005-e7f8e01c93cc

My repo: <https://github.com/Fortune117/sbox-scenestaging/tree/dark-descent>

**Comment by garrynewman** [comment]
Does the value change in the json file?

**Comment by Fortune117** [comment]
> Does the value change in the json file?

No, but I've just noticed it seems to happen when the component is disabled:

https://github.com/Facepunch/sbox-scenestaging/assets/7847372/69b76964-3d2d-4bab-80ea-603077a474fb

**Comment by garrynewman** [comment]
Fixed in latest
