### ISSUE TITLE
Issues Placing a Prefab in the Scene

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-scenestaging#51]
https://github.com/Facepunch/sbox-scenestaging/assets/7847372/16c6f136-feee-453e-a25f-b99285fefafd

**Comment by CarsonKompon** [comment]
Can confirm this happens all the time for me as well

**Comment by bub-bl** [comment]
@garrynewman , Can you review this code and push it, if it's good for you ?

The following code add a way to enable this optionally

- Go to \sbox\addons\tools\code\Editor\EditorPreferences\EditorPreferences.cs
- Go to line 53
- Add the following code:
```csharp
        [Title("Rotate On Hit Position")]
	public static bool RotateGameObjectOnHitPosition
	{
		get => EditorCookie.Get( "RotateGameObjectOnHitPosition", false );
		set => EditorCookie.Set( "RotateGameObjectOnHitPosition", value );
	}
```
---
- Go to \sbox\addons\tools\code\Editor\EditorPreferences
- Create a new C# file called `PageScene.cs` with the following code:
```csharp
internal class PageScene : Widget
{
	public PageScene( Widget parent ) : base( parent )
	{
		Layout = Layout.Column();
		Layout.Margin = 34;

		var sheet = Layout.Add( new PropertySheet( this ) );
		
		sheet.AddRow( new Label.Subtitle( "Game Objects" ) );
		{
			sheet.AddStaticProperty( typeof( EditorPreferences ), nameof( EditorPreferences.RotateGameObjectOnHitPosition ) );
		}
	}
}
```
---
- Go to \sbox\addons\tools\code\Editor\EditorPreferences\EditorPreferencesWindow.cs
- Go to line 38
- Add the following code:
```csharp
container.AddPage( "Scene", "grid_4x4", new PageScene( this ) );
```
---
- Go to \sbox-scenestaging\code\Editor\SceneView\SceneViewWidget.cs
- Go to line 217
- Replace the line with the following code:
```csharp
if (EditorPreferences.RotateGameObjectOnHitPosition )
    DragObject.Transform.Rotation = rot;
```

Result in video: 
https://streamable.com/4xeoxs

**Comment by garrynewman** [comment]
Can you give this another try with the latest code. I switched to use physics trace instead of scene trace, so I would expect hit normals to be a lot smoother.

**Comment by Fortune117** [comment]
Seems more or less the same:

https://github.com/Facepunch/sbox-scenestaging/assets/7847372/4b72a938-520a-4361-a32e-30064ab3bd76

**Comment by garrynewman** [comment]
What is it hitting? Is the ground all bumpy?

**Comment by Fortune117** [comment]
> What is it hitting? Is the ground all bumpy?

The ground is just a flat plane. Could it be taking the normal map of the material into account somehow?

**Comment by garrynewman** [comment]
I think I know what this is. I think the placement trace is probably hitting the object you're dragging in, because I'm not setting the dragging tag on the child objects of the dragging object.
