### ISSUE TITLE
 [Event.Hotload] attribute is not triggered anymore when code hot reload

### ISSUE THREAD

**Issue by bub-bl** [Facepunch/sbox-scenestaging#53]

**Comment by garrynewman** [comment]
Works for me?

**Comment by bub-bl** [comment]
The Hotload only work with static methods ?

Only my static functions is called when Hotload is triggered in my code:
```csharp
public class MyComponent : BaseComponent
{    
    public override void OnStart()
    {
        
    }

    // Never called
    [Event.Hotload]
    public void Hotload()
    {
        Log.Info("Hotload");
    }
    
    [Event.Hotload]
    public static void StaticHotload()
    {
        Log.Info("Static Hotload");
    }
}
```

In this file `code/Editor/ProjectSettings/ProjectSettings.cs`, you use [Event.Hotload] on a non static method. I have put a Log.Info() inside of this method, and he is never called when Hotload is triggered.
```csharp
/// <summary>
/// Rebuild the page on hotload for quick iteration
/// </summary>
[Event.Hotload]
public void Reset()
{
    HeaderLayout.Clear( true );
    BodyLayout.Clear( true );
    FooterLeft.Clear( true );
    FooterRight.Clear( true );

    InitFromProject( Project );
}
```

I think my code is right ??

**Comment by garrynewman** [comment]
Components aren't enrolled into the Event system (Event.Register).. and there aren't any plans to automatically enroll them all right now.
