### ISSUE TITLE
Unfocus selected Game Objects in scene when focus any element in Assets Browser

### ISSUE THREAD

**Issue by bub-bl** [Facepunch/sbox-scenestaging#57]
When a GameObject is selected in the scene, if i press DEL key on any asset in Assets Browser, my file is not deleted, but the selected GameObject is removed from the scene. This is pretty anoying :laughing:

**Comment by garrynewman** [comment]
I hit this too. Same thing with Ctrl+C not working in console. Some weird priorities happening.
