### ISSUE TITLE
Context menu opens on second monitor by default

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-scenestaging#61]
If your inspector is near a secondary monitor your context menu will open there.
Image below shows right clicking a component.
![image](https://github.com/Facepunch/sbox-scenestaging/assets/59583743/da77bb3a-ad7f-4fa0-9f36-2d3dbaa2458e)

This only happens when you right clicked near enough the edge so that the context menu doesn't have space.
Image below shows right clicking a component but far enough from the edge.
![image](https://github.com/Facepunch/sbox-scenestaging/assets/59583743/e778a503-389e-4a6d-9a10-92ff0c23c5dc)

**Comment by DevulTj** [comment]
This should be fine now

**Comment by yuberee** [comment]
Seems to be fine for components, but still happens for properties.
![image](https://github.com/Facepunch/sbox-scenestaging/assets/59583743/d1a5c369-c1cc-4a91-aa56-21a67aba49d1)

**Comment by DevulTj** [comment]
I'll sort this tomorrow. It should be fine for every other Menu that is created in scenestaging except that.

**Comment by DevulTj** [comment]
Sorry for the wait, this should all be good now.
