### ISSUE TITLE
Shortcut priority problem in scene

### ISSUE THREAD

**Issue by bub-bl** [Facepunch/sbox-scenestaging#69]
If I select my gameobject, since I click on a field in the inspector (the value is not selected), the shortcut CTRL + C copies the value of the field and not the gameobject. Which forces me to deselect my gameobject, then re-select it to copy/paste it

https://streamable.com/f16f5a

**Comment by garrynewman** [comment]
I believe I fixed this a couple of weeks ago - is it still the case?
