### ISSUE TITLE
Expose prefab components in scene inspector

### ISSUE THREAD

**Issue by bub-bl** [Facepunch/sbox-scenestaging#72]
When we place a prefab in the scene, we edit the main prefab directly. It would be interesting to make the instance of a prefab editable, as well as these components

![image](https://github.com/Facepunch/sbox-scenestaging/assets/66354328/e5af2aef-5e3a-4c61-a281-476ce7d03f31)

**Comment by garrynewman** [comment]
What would happen when the prefab gets changed?

**Comment by bub-bl** [comment]
I'm stupid, I'm confusing it with something else :|
I close this issue
