### ISSUE TITLE
Need to restart S&box editor to update new input

### ISSUE THREAD

**Issue by bub-bl** [Facepunch/sbox-scenestaging#73]
![image](https://github.com/Facepunch/sbox-scenestaging/assets/66354328/63c9a0da-f990-46c7-bc20-1d1d6bd993a8)
![image](https://github.com/Facepunch/sbox-scenestaging/assets/66354328/4d00f64d-a0f6-42ea-94bd-700111d73800)

**Comment by DevulTj** [comment]
I haven't been able to reproduce this yet

**Comment by CarsonKompon** [comment]
Can confirm this was happening to me too. Adding a new input bind or changing an existing one would require an editor restart before it actually lets me use that input. This has been an issue long before scene so it's probably not scene-related.

**Comment by CarsonKompon** [comment]
This is no longer happening to me as of this morning. Might of had something to do with me removing a few projects from my editor launcher if no fixes were made since my last comment 😅
