### ISSUE TITLE
Anime / TFS2 shaders don't work with directional lights

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-scenestaging#82]
The scene shown has just a single directional light, and the models show as pitch black.
https://github.com/Facepunch/sbox-scenestaging/assets/94070205/348ee374-7c83-42e4-ba36-209da2d6d5c3
When the point light is turned on, they're lit up properly.

**Comment by handsomematt** [comment]
Does this happen with shaders you have made, those seem to be old shaders that also have custom lighting models of their own... It's possible they've just fucked it.

**Comment by handsomematt** [comment]
Idk we dont make the anime or tf2 shaders
