### ISSUE TITLE
Scene Capsule & Sphere Trace issues

### ISSUE THREAD

**Issue by SaintlyDem0nic** [Facepunch/sbox-scenestaging#85]
When getting the PhysicsTraceResult of a Sphere Trace, The results do not act as expected. Below is a image of most of the TraceResults printed.

![image](https://github.com/Facepunch/sbox-scenestaging/assets/57987470/156893e7-f6bf-4473-8fcd-f4ac88d2fc29)
_Most are default values, aside from the EndPosition and HitPosition (represented by the blue Gizmo Sphere) which return the center of the sphere._

When doing the same on a capsule trace, the PhysicsTraceResult are about the same result except the EndPosition and HitPosition are defaulted to a Vector3(0,0,0) as well.
![image](https://github.com/Facepunch/sbox-scenestaging/assets/57987470/f8dc5783-ca41-4dea-b12d-61a6b5d7dbfc)

I didn't test this on a sweep trace. A Ray trace works fine.

Code used:

```
var capsule = new Capsule();
var pos = GameObject.Transform.Position;
capsule.Radius = Radius;
capsule.CenterA = pos + new Vector3( Width / 2, 0 );
capsule.CenterB = pos + new Vector3( -(Width / 2), 0, 0 );

if ( Sphere )
{
	Trace = Scene.PhysicsWorld.Trace.Sphere( Radius, pos, pos )
		.WithAllTags( "world" )
		.Run();
}
else
{
	Trace = Scene.PhysicsWorld.Trace.Capsule( capsule )
	.WithAllTags( "world" )
	.Run();
}

if ( Trace.Hit )
{
	if ( Sphere )
		Log.Error( "-------SPHERE--------" );
	else
		Log.Error( "-------Capsule-------" );

	Log.Warning( "Hit Detected: " + Trace.Hit );
	Log.Warning( "Hit Position: " + Trace.HitPosition );
	Log.Warning( "End Position: " + Trace.EndPosition );
	Log.Warning( "Fraction: " + Trace.Fraction );
	Log.Warning( "Distance: " + Trace.Distance );
	Log.Warning( "Direction: " + Trace.Direction );
	Log.Warning( "Triangle: " + Trace.Triangle);

	Gizmo.Draw.Color = Color.Blue;
	Gizmo.Draw.SolidSphere( Trace.HitPosition, 3f );

        Gizmo.Draw.Color = Color.Green;
	Gizmo.Draw.SolidSphere( Trace.EndPosition, 3f );
}
```

**Comment by garrynewman** [comment]
With the sphere, you're not actually tracing, so it seems like those values are correct - assuming it's starting in solid.

You're not tracing on the capsule either - but I agree that those values make no sense.

**Comment by SaintlyDem0nic** [comment]
I was just confused why the Capsule was not mirroring the functionality of the Sphere.

**Comment by dictateurfou** [comment]
For my part I don't know if this will help you but I had an almost similar problem.
Exemple work all time :
var tr = Physics.Trace.Ray( Eye.Transform.Position, targetPos ).WithoutTags( "player" ).Radius( 8 ).Run();
And this not work all time in a certain place it sends me the endpos at 0, 0, 0 even though there is no reason
Scene.PhysicsWorld.Trace.Ray( Eye.Transform.Position, targetPos ).WithoutTags( "player" )

**Comment by garrynewman** [comment]
These are both unified now, so their behaviour should be the same
