### ISSUE TITLE
[Request]  put the properties of a component in order

### ISSUE THREAD

**Issue by dictateurfou** [Facepunch/sbox-scenestaging#89]
I don't know if it's because of my partial class, but the properties are mixed

exemple:
![04e569bbea5498bb7ba5ff408dbcb347](https://github.com/Facepunch/sbox-scenestaging/assets/12927420/577aeeb0-8545-4aa2-bd41-2eb2fe1a5679)

**Comment by garrynewman** [comment]
Properties are in file line order. Either order them in a file, or use group attributes

**Comment by dictateurfou** [comment]
ho yes he have better look with group thanks
![9ff45018424313a1c216ce2bad7e8064](https://github.com/Facepunch/sbox-scenestaging/assets/12927420/0061d63a-ad44-49c8-ad1b-53e6f9b74617)
