### ISSUE TITLE
Css styles not updated on other connected clients when HotReload

### ISSUE THREAD

**Issue by bub-bl** [Facepunch/sbox-scenestaging#95]
Imported scss from `@import "/styles/my_scss_file.scss" seam to be not loaded to on second client.

https://github.com/Facepunch/sbox-scenestaging/assets/66354328/77f70df0-c16a-4e1a-8bef-7f9c5728d662

**Comment by garrynewman** [comment]
Fix path for facepunch:

- [ ] Implement GameMenuDll.FilesTable (look at AssemblyTable)
- [ ] On start, put all .scss files in FilesTable (unless they're in a package)
- [ ] Allow loading .scss files from FilesTable (Memory bases filesystem)
- [ ] Update them on change
